DELETE FROM ALBUMPOST;
DELETE FROM USERALBUMS;
DELETE FROM PERSONNALPOST;
DELETE FROM ALBUM;
DELETE FROM USER;
ALTER TABLE ALBUM AUTO_INCREMENT = 1;
ALTER TABLE PERSONNALPOST AUTO_INCREMENT = 1;
ALTER TABLE USER AUTO_INCREMENT = 1;