INSERT INTO ALBUM VALUES (1,'Album 1',true);
INSERT INTO USERALBUMS VALUES (1,1);
INSERT INTO ALBUM VALUES (2,'Album 2',true);
INSERT INTO USERALBUMS VALUES (1,2);

INSERT INTO PERSONNALPOST VALUES (1,'linkexample','description example','image','text');
INSERT INTO ALBUMPOST VALUE (1,1);
INSERT INTO PERSONNALPOST VALUES (2,'linkexample','description example','image','text');
INSERT INTO ALBUMPOST VALUE (1,2);